/* GENERATED by build.mjs from products.json — do not edit by hand. */
window.PRODUCTS = [
  {
    "id": 1,
    "slug": "instant-electric-water-heater-tap-digital-display",
    "sku": "HRL-WH-001",
    "brand": "Generic",
    "category": "WaterHeaters",
    "stock": 12,
    "warranty": "12 months manufacturer replacement warranty.",
    "title": {
      "en": "Instant Electric Water Heater Tap - Digital Display",
      "ur": "انسٹنٹ الیکٹرک واٹر ہیٹر ٹیپ - ڈیجیٹل ڈسپلے"
    },
    "price": 2499,
    "oldPrice": 4500,
    "summary": {
      "en": "Instant hot water within 3 seconds for kitchens and bathrooms. 3000W heating element with a digital LED temperature display.",
      "ur": "رسوئی اور باتھ روم کے لیے 3 سیکنڈ میں گرم پانی۔ 3000W ہیٹنگ ایلیمینٹ اور ڈیجیٹل LED ٹمپریچر ڈسپلے۔"
    },
    "features": {
      "en": [
        "3000W high-power instant heating",
        "Digital LED temperature display",
        "360 degree rotating nozzle head",
        "Waterproof and shockproof design",
        "Fits standard kitchen and bathroom tap fittings"
      ],
      "ur": [
        "3000W تیز ہیٹنگ",
        "ڈیجیٹل LED ٹمپریچر ڈسپلے",
        "360 ڈگری گھومنے والا نوزل",
        "واٹر پروف اور شاک پروف ڈیزائن",
        "معیاری کچن اور باتھ روم ٹیپ فٹنگ کے مطابق"
      ]
    },
    "specs": {
      "Power": "3000W",
      "Voltage": "220V AC 50Hz",
      "Display": "Digital LED",
      "Material": "ABS + Stainless steel"
    },
    "images": [
      "images/products/instant-electric-water-heater-tap-1.svg",
      "images/products/instant-electric-water-heater-tap-2.svg",
      "images/products/instant-electric-water-heater-tap-3.svg"
    ],
    "variants": [
      {
        "name": "White / 1 Pcs",
        "extraCost": 0
      }
    ]
  }
];
window.CATEGORIES = [
  {
    "id": "All",
    "en": "All Products",
    "ur": "تمام پروڈکٹس"
  },
  {
    "id": "Inverters",
    "en": "Inverters",
    "ur": "انورٹرز"
  },
  {
    "id": "Chargers",
    "en": "Battery Chargers",
    "ur": "بیٹری چارجرز"
  },
  {
    "id": "Solar",
    "en": "Solar Accessories",
    "ur": "سولر ایکسیسریز"
  },
  {
    "id": "WaterHeaters",
    "en": "Water Heaters",
    "ur": "واٹر ہیٹرز"
  }
];
